language: java
jdk: openjdk11
sudo: false
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - pod install sonarqube
  - sonar start
script:
  - mvn clean verify
  - mvn sonar:sonar
