os: osx
language: java
jdk: openjdk11
sudo: false

env:
  global:
    - CODECOV_TOKEN=:67b28199-7915-444e-899c-2f8114b9c309

before_script:
  - pip install --user codecov

script:
  - mvn clean verify

after_success:
  - codecov