language: java
jdk: openjdk11
sudo: false

env:
  global:
    - CODECOV_TOKEN=:67b28199-7915-444e-899c-2f8114b9c309

script:
  - mvn clean verify

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 67b28199-7915-444e-899c-2f8114b9c309