package it.polimi.ingsw.client.controllers;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import it.polimi.ingsw.client.controllers.base.BaseViewController;
import it.polimi.ingsw.client.controllers.base.NavigationController;
import it.polimi.ingsw.client.views.boards.GameBoard;
import it.polimi.ingsw.client.views.boards.GameBoardListener;
import it.polimi.ingsw.server.models.GameImpl;
import org.jetbrains.annotations.NotNull;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Optional;
import java.util.UUID;

public class GameViewController extends BaseViewController implements GameBoardListener {
    public static final int HEIGHT = 800;
    public static final int WIDTH = (int) (HEIGHT * 1.375);

    private JPanel panel;
    private GameBoard gameBoard;
    private NavigationController playerNavigationController;

    public GameViewController(@NotNull NavigationController navigationController) {
        super("Gioca", WIDTH, HEIGHT, navigationController);
        $$$setupUI$$$();
        setContentPane(panel);
    }

    @Override
    protected void onShow() {
        playerNavigationController = new NavigationController(PlayerBoardViewController.class);
        getPlayerBoardViewController().ifPresent(e -> e.setGameViewController(this));
    }

    @Override
    public void controllerPopped() {
        getPlayerBoardViewController().ifPresent(e -> e.setGameViewController(null));
        Optional.ofNullable(playerNavigationController).ifPresent(NavigationController::close);
        playerNavigationController = null;
    }

    public void playerBoardViewControllerPopped() {
        playerNavigationController = null;
        getNavigationController().popViewController();
    }

    private @NotNull Optional<PlayerBoardViewController> getPlayerBoardViewController() {
        try {
            return Optional.of((PlayerBoardViewController) playerNavigationController.getViewController(0));
        } catch (Exception e) {
            return Optional.empty();
        }
    }

    private void createUIComponents() {
        try {
            gameBoard = new GameBoard(new Dimension(WIDTH, (int) (HEIGHT * 0.98)), GameImpl.Creator.newGame(UUID.randomUUID(), new ArrayList<>()));
            gameBoard.setBoardListener(this);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel.add(gameBoard, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}