package it.polimi.ingsw.client.controllers.game;

import it.polimi.ingsw.client.controllers.base.BaseViewController;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;
import org.jetbrains.annotations.NotNull;

import javax.swing.*;

public class PdfViewController extends BaseViewController {
    private JPanel panel;

    private String url;

    public PdfViewController(@NotNull Object... args) {
        super("Regole", 1000, 800, null);
        url = (String) args[0];
        $$$setupUI$$$();
        setContentPane(panel);
        setResizable(true);
        setEnableFullscreen(true);
    }

    private void createUIComponents() {
        var controller = new SwingController();
        controller.openDocument(url);
        panel = new SwingViewBuilder(controller).buildViewerPanel();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
